language: python
python:
  - "2.7"

# install dependencies
install: "pip install -r requirements.txt"

# run tests
script: fab test

# coveralls
after-success:
  - coveralls

# notify chat
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c0849ac69ee62ba4192c
    on_success: always
    on_failure: always
    on_start: never
