language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

# install dependencies
install: "pip install -r requirements.txt"

# run tests
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

# coveralls
after_success:
  - coveralls

# notify chat
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c0849ac69ee62ba4192c
    on_success: always
    on_failure: always
    on_start: never
